### ISSUE TITLE
Apps couldn't be loaded: [kvs,mnesia]

### ISSUE THREAD

**Issue by emprovements** [synrc/n2o#301] opened 2018-01-22 10:18 UTC
Hi,
I am trying to run the sample on Alpine Linux 3.4.6 but I am getting this printout: Apps couldn't be loaded: [kvs,mnesia]
and I cannot query the port 8000. Also netstat shows nothing.

Here are some info about Alpine:
Linux version 4.4.0-109-generic (buildd@lgw01-amd64-038) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018

Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]
Eshell V7.3.1

And here is the issue:
```
n2o:~/n2o/samples$ ./mad deps compile plan repl
==> dependency: "git://github.com/uwiger/gproc" tag: {tag,"0.6.1"}
==> dependency: "git://github.com/synrc/rest" tag: {tag,"2.9"}
==> dependency: "git://github.com/evanmiller/erlydtl" tag: {tag,"0.8.0"}
==> dependency: "git://github.com/synrc/nitro" tag: {tag,"2.4"}
==> dependency: "git://github.com/synrc/mad" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/sh" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/fs" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/active" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/avz" tag: {tag,"4.4"}
==> dependency: "git://github.com/synrc/n2o" tag: {tag,"4.4"}
==> dependency: "git://github.com/extend/cowboy" tag: {tag,"1.0.1"}
==> dependency: "git://github.com/ninenines/cowlib.git" tag: "1.0.0"
==> dependency: "git://github.com/ninenines/ranch.git" tag: "1.0.0"
==> dependency: "git://github.com/synrc/kvs" tag: {tag,"3.9.1"}
==> dependency: "git://github.com/tim/erlang-oauth" tag: {tag,"v1.6.0"}
==> dependency: "git://github.com/sile/jsone.git" tag: {tag,"v0.3.3"}
==> "gproc"
==> "rest"
==> "erlydtl"
==> "nitro"
==> "mad"
==> "sh"
==> "fs"
==> "active"
==> "avz"
==> "n2o"
==> "cowboy"
==> "cowlib"
==> "ranch"
==> "kvs"
==> "oauth"
==> "jsone"
==> "/home/mg/n2o/samples"
==> "/home/mg/n2o/samples/apps"
==> "/home/mg/n2o/samples/apps/review"
OK
Ordered: [mnesia,asn1,kernel,stdlib,kvs,fs,ranch,compiler,syntax_tools,crypto,
          inets,cowlib,public_key,cowboy,n2o,review,active,avz,erlydtl,gproc,
          jsone,mad,nitro,oauth,rest,sh]
OK
Configuration: [{n2o,
                    [{port,8000},
                     {app,review},
                     {upload,"./apps/review/priv/static/"},
                     {search,
                         "/Users/5HT/depot/synrc/synrc.com/apps/*/doc/web/*.htm"},
                     {mode,dev},
                     {route,routes},
                     {mq,n2o_mq},
                     {formatter,bert},
                     {minify,
                         {"apps/review/priv/static",
                          ["deps/n2o/priv/bullet.js","deps/n2o/priv/n2o.js",
                           "deps/n2o/priv/ftp.js",
                           "deps/n2o/priv/protocols/bert.js",
                           "deps/n2o/priv/protocols/nitrogen.js",
                           "deps/n2o/priv/utf8.js",
                           "deps/n2o/priv/validation.js"]}},
                     {log_modules,config},
                     {log_level,config},
                     {log_backend,n2o_io},
                     {session,n2o_session},
                     {origin,<<"*">>},
                     {bridge,n2o_cowboy},
                     {pickler,n2o_pickle},
                     {erroring,n2o_error},
                     {event,pickle}]},
                {avz,
                    [{after_login_page,"/index"},
                     {login_page,"/interlogin"},
                     {fb_id,"176025532423202"},
                     {tw_consumer_key,"YwfU5qj5AYY0uwPumcw1Q"},
                     {tw_consumer_secret,
                         "O7VjRYLWxwMgtSXZbiiY6kc1Og2il9gbo1KAIqZk"},
                     {g_client_id,
                         "158344909038-j6c0rbvpi09kdaqq03j2eddlf047ht3d.apps.googleusercontent.com"},
                     {g_cookiepolicy,"http://localhost:8000"},
                     {g_btn_width,240},
                     {g_btn_height,50},
                     {g_btn_theme,"light"},
                     {g_btn_longtitle,true},
                     {github_client_id,"591bfe2556ee60ca8c32"},
                     {github_client_secret,
                         "01411884e3c51624d3ea729ed6b047db52973e8e"},
                     {ms_client_id,"54385d15-f1e0-4fcf-9bf4-042d740e0df4"},
                     {ms_client_secret,"jU0tStEzRdDPFwL9NdVGYxo"},
                     {ms_redirect_uri,"http://localhost:8000/interlogin"}]},
                {kvs,
                    [{dba,store_mnesia},
                     {schema,[kvs_user,kvs_acl,kvs_feed,kvs_subscription]}]}]
Applications: [mnesia,asn1,kernel,stdlib,kvs,fs,ranch,compiler,syntax_tools,
               crypto,inets,cowlib,public_key,cowboy,n2o,review,active,avz,
               erlydtl,gproc,jsone,mad,nitro,oauth,rest,sh]
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V7.3.1  (abort with ^G)
1> n2o_async:Async Start Attempt {handler,"timer",n2o,system,n2o,[],[]}

==> "samples"
==> "/home/mg/n2o/samples"
==> "gproc"
==> "rest"
==> "erlydtl"
==> "nitro"
==> "mad"
==> "sh"

Apps couldn't be loaded: [kvs,mnesia]
Setting up watches.  Beware: since -r was given, this may take a while!
                                                                       Watches established.
                                                                                           ==> "fs"
==> "active"
==> "avz"
==> "n2o"
==> "cowboy"
==> "cowlib"
==> "ranch"
==> "kvs"
==> "oauth"
==> "jsone"
==> "/home/mg/n2o/samples/apps"
==> "/home/mg/n2o/samples/apps/review"
```

**Comment by 5HT** [comment] 2018-01-22 15:12
This is not a bug if you have no mnesia.
Try to check:

> application:start(mnesia).

if it fails, close the issue :-)

**Comment by emprovements** [comment] 2018-01-22 15:23
No, it is not failing. But maybe I am doing something wrong. I just started with Erlang.
```
Eshell V7.3.1  (abort with ^G)
1> application:start(mnesia)
1>
```

**Closed** 2018-01-22 15:24 UTC

**Comment by emprovements** [comment] 2018-01-22 15:25
Ok, it failed. I am sorry for inconvenience. I just started with Erlang.
